-- 1. Create account_type ENUM
DROP TYPE IF EXISTS public.account_type CASCADE;
CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');

-- 2. Table structure for 'classification'
DROP TABLE IF EXISTS public.classification CASCADE;
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name VARCHAR NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- 3. Table structure for 'inventory'
DROP TABLE IF EXISTS public.inventory CASCADE;
CREATE TABLE public.inventory (
    inv_id INT GENERATED BY DEFAULT AS IDENTITY,
    inv_make VARCHAR NOT NULL,
    inv_model VARCHAR NOT NULL,
    inv_year SMALLINT NOT NULL,
    inv_description TEXT NOT NULL,
    inv_image VARCHAR NOT NULL,
    inv_thumbnail VARCHAR NOT NULL,
    inv_price NUMERIC(9,0) NOT NULL,
    inv_miles INT NOT NULL,
    inv_color VARCHAR NOT NULL,
    classification_id INT NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id),
    CONSTRAINT fk_classification FOREIGN KEY (classification_id)
        REFERENCES public.classification (classification_id)
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

-- 4. Table structure for 'account'
DROP TABLE IF EXISTS public.account CASCADE;
CREATE TABLE public.account (
    account_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_firstname VARCHAR NOT NULL,
    account_lastname VARCHAR NOT NULL,
    account_email VARCHAR NOT NULL UNIQUE,
    account_password VARCHAR NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client',
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- 5. Insert data into 'classification'
INSERT INTO public.classification (classification_name)
VALUES 
    ('Custom'),
    ('Sport'),
    ('SUV'),
    ('Truck'),
    ('Sedan');

-- 6. Insert data into 'inventory'
INSERT INTO public.inventory (
    inv_make, inv_model, inv_year, inv_description, 
    inv_image, inv_thumbnail, inv_price, inv_miles, 
    inv_color, classification_id
)
VALUES
    ('Chevy','Camaro',2018,
     'If you want to look cool this is the car you need! Great performance at an affordable price.',
     '/images/vehicles/camaro.jpg','/images/vehicles/camaro-tn.jpg',25000,101222,'Silver',2),

    ('Batmobile','Custom',2007,
     'Ever wanted to be a superhero? Now you can with the Batmobile. It even switches to bike mode to cut through traffic.',
     '/images/vehicles/batmobile.jpg','/images/vehicles/batmobile-tn.jpg',65000,29887,'Black',1),

    ('FBI','Surveillance Van',2016,
     'Do you like police shows? Feel right at home driving this van, complete with surveillance equipment (extra $2,000/month).',
     '/images/vehicles/survan.jpg','/images/vehicles/survan-tn.jpg',20000,19851,'Brown',1),

    ('Dog','Car',1997,
     'Straight from Aspen, Colorado – the original Dog Car complete with fluffy ears.',
     '/images/vehicles/dog-car.jpg','/images/vehicles/dog-car-tn.jpg',35000,71632,'White',1),

    ('Jeep','Wrangler',2019,
     'Compact and powerful. Perfect for everyday driving as well as off-roading, on rocks or in the mud.',
     '/images/vehicles/wrangler.jpg','/images/vehicles/wrangler-tn.jpg',28045,41205,'Yellow',3),

    ('Lamborghini','Adventador',2016,
     'This V-12 engine packs a punch. Wear your seatbelt and obey all traffic laws!',
     '/images/vehicles/adventador.jpg','/images/vehicles/adventador-tn.jpg',417650,71003,'Blue',2),

    ('Aerocar International','Aerocar',1963,
     'Tired of traffic? This car converts into an airplane. Only 6 were ever made.',
     '/images/vehicles/aerocar.jpg','/images/vehicles/aerocar-tn.jpg',700000,18956,'Red',1),

    ('Monster','Truck',1995,
     'Not for work – for FUN. 60 inch tires give you the traction you need for stunts in mud.',
     '/images/vehicles/monster-truck.jpg','/images/vehicles/monster-truck-tn.jpg',150000,3998,'Purple',1),

    ('Cadillac','Escalade',2019,
     'Stylish and luxurious – from the beach to the White House.',
     '/images/vehicles/escalade.jpg','/images/vehicles/escalade-tn.jpg',75195,41958,'Black',4),

    ('GM','Hummer',2016,
     'Perfect for large families who love off-roading. Strong enough for mud and rocky terrain.',
     '/images/vehicles/hummer.jpg','/images/vehicles/hummer-tn.jpg',58800,56564,'Yellow',4),

    ('Mechanic','Special',1964,
     'Needs some TLC, but with love it will run as good as new.',
     '/images/vehicles/mechanic.jpg','/images/vehicles/mechanic-tn.jpg',100,200125,'Rust',5),

    ('Ford','Model T',1921,
     'The first mass-produced car. Available in any color as long as it’s black.',
